#!/bin/sh
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

PATH="./node_modules/.bin:$PATH"  

# Perform lint check on files in the staging area through .lintstagedrc configuration
yarn run lint-staged